blog-after/config/routes.rb
Blog::Application.routes.draw do
  root to: 'articles#index'
  resources :articles
  resources :comments
end

blog-after/app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :author
  has_many :comments

  include Tire::Model::Search
  include Tire::Model::Callbacks
  
  def self.search(params)
    tire.search(load: true) do
      query { string params[:query], default_operator: "AND" } if params[:query].present?
      filter :range, published_at: {lte: Time.zone.now}
    end
  end
end

blog-after/app/models/author.rb
class Author < ActiveRecord::Base
end

blog-after/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

blog-after/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

blog-after/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.search(params)
  end
  
  def show
    @article = Article.find(params[:id])
    @comment = Comment.new(article_id: @article.id)
  end
end

blog-after/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end
  
  def create
    @comment = Comment.new(params[:comment])
    if @comment.save
      redirect_to @comment.article, notice: "Successfully created comment."
    else
      render :new
    end
  end
end

blog-after/app/helpers/application_helper.rb
module ApplicationHelper
end

blog-after/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog-after/app/helpers/comments_helper.rb
module CommentsHelper
end

blog-after/app/views/articles/index.html.erb
<h1>Articles</h1>

<%= form_tag articles_path, method: :get do %>
  <p>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>

<div id="articles">
<% @articles.each do |article| %>
  <h2>
    <%= link_to article.name, article %>
    <span class="comments">(<%= pluralize(article.comments.size, 'comment') %>)</span>
  </h2>
  <div class="info">
    by <%= article.author.name %>
    on <%= article.published_at.strftime('%b %d, %Y') %>
  </div>
  <div class="content"><%= article.content %></div>
<% end %>
</div>

blog-after/app/views/articles/show.html.erb
<h1><%= @article.name %></h1>

<p class="author"><em>by <%= @article.author.first_name %> <%= @article.author.last_name %></em></p>

<%= simple_format @article.content %>

<p><%= link_to "Back to Articles", articles_path %></p>

<% unless @article.comments.empty? %>
  <h2><%= pluralize(@article.comments.size, 'comment') %></h2>

  <div id="comments">
  <% for comment in @article.comments %>
    <div class="comment">
      <strong><%= comment.name %></strong>
      <em>on <%= comment.created_at.strftime('%b %d, %Y') %></em>
      <%= simple_format comment.content %>
    </div>
  <% end %>
  </div>
<% end %>

<h3>Add your comment:</h3>
<%= render "comments/form" %>

blog-after/app/views/comments/_form.html.erb
<%= form_for @comment do |f| %>
  <% if @comment.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :article_id %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content, "Comment" %><br />
    <%= f.text_area :content, :rows => 12, :cols => 35 %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

blog-after/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

blog-after/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>